### ISSUE TITLE
sqlalchemy.exc.internalerror Access denied

### ISSUE THREAD

**Issue by justaboredkid** [saurabhshri/ccextractor-web#20]
When running 'run.py' and accessing 127.0.0.1:5000, I got this:
```
Traceback (most recent call last):
  File "/home/----/.local/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/----/.local/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/----/.local/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/----/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/----/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/----/.local/lib/python3.5/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/home/----/.local/lib/python3.5/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/home/----/ccextractor-web/run.py", line 214, in before_first_request
    db.create_all()
  File "/home/----/.local/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 963, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/----/.local/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 955, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 4005, in create_all
    tables=tables)
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1939, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1932, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1193, in _do_get
    self._dec_overflow()
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1190, in _do_get
    return self._create_connection()
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/----/.local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/----/.local/lib/python3.5/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/----/.local/lib/python3.5/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "/home/----/.local/lib/python3.5/site-packages/pymysql/connections.py", line 598, in connect
    self._request_authentication()
  File "/home/----/.local/lib/python3.5/site-packages/pymysql/connections.py", line 852, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/----/.local/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/----/.local/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/----/.local/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1698, "Access denied for user 'root'@'localhost'") (Background on this error at: http://sqlalche.me/e/2j85)
```
The web page also show the error, like this:
![screenshot from 2018-11-25 18-51-50](https://user-images.githubusercontent.com/29010153/48990427-3e674d80-f0e3-11e8-9fa7-c6119be68f7b.png)

I'm using python 3.5.3 on Devuan. Also, I was using a X11 forwarded Firefox tunnelled using ssh.

**Comment by saurabhshri** [comment]
> sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1698, "Access denied for user 'root'@'localhost'") (Background on this error at: http://sqlalche.me/e/2j85)

Are you sure you've set correct URI for your MySQL database in the configuration file? https://github.com/saurabhshri/ccextractor-web/blob/development/instance/config.py#L24

**Comment by justaboredkid** [comment]
🤦 I should have read the instruction thoroughly. Thanks. At least if someone else make the same mistake, they can find this.
